theme: jekyll-theme-minima
title: Challenge Suite
description: A suite of software to run Schala's souped up Rivet coding challenge
url: https://schala.github.io/challenge-suite
baseurl: /challenge-suite
permalink: /:title
